---Start Logging---
138098.734375 - Util Init
138098.921875 - splashScreen Loaded
138102.40625 - modules Imported
138102.421875 - vars Defined
138108.0625 - plots Defined
138108.125 - functions Defined
138108.15625 - Start Loading UI138108.578125 - End Drawing UI138112.28125 - Start Checking Network
138122.453125 - refresh Error
138127.265625 - refresh Error
138128.140625 - refresh Error
138132.921875 - refresh Error
138137.546875 - refresh Error
138142.265625 - refresh Error
138147.046875 - refresh Error
138171.765625 - Start Checking Network
138180.109375 - refresh Error
138199.625 - Start Checking Network
138203.0 - refresh Error
138203.28125 - Start Logining
138203.65625 - .length = 23
138203.65625 - contentlength = 23
138203.765625 - ReLogin
138204.203125 - .length = 1194
138204.21875 - contentlength = 1194
138204.796875 - .length = None
138204.8125 - contentlength = None
138210.015625 - Getting UserPLs
138210.234375 - .length = 36
138210.25 - contentlength = 36
138210.296875 - @ Error :
138210.296875 - exceptions.Exception: playlist
@ Traceback (most recent call last):
@   File "E:\private\fd8f9a7e\default.py", line 1104, in getUserPLs
@     userPlaylists = nma.getUserPLs()['playlist']
@ KeyError: playlist
@ Traceback (most recent call last):
@   File "E:\private\fd8f9a7e\default.py", line 1873, in startConn
@     @ refreshUserPLs()
@   File "E:\private\fd8f9a7e\default.py", line 1123, in refreshUserPLs
@     @ updateUserPLs()
@   File "E:\private\fd8f9a7e\default.py", line 1119, in updateUserPLs
@     @ playlistListbox.set_list(playlistListbox_)
@   File ".\appuifw2.py", line 453, in set_list
@   File ".\appuifw2.py", line 406, in __set_items
@ ValueError@ : @ non-empty list expected@ 
138383.125 - refresh Error
215534.78125 - refresh Error
215537.71875 - ===== End ======
